sudo: false
language: ruby
rvm:
  - 2.2.10
  - 2.3.8
  - 2.4.5
  - 2.5.3
  - 2.6.0
  - ruby-head
before_install:
  - travis_retry gem update --system || travis_retry gem update --system 2.7.8
  - gem update --remote bundler

gemfile:
  - gemfiles/Gemfile-rails5.0.x
  - gemfiles/Gemfile-rails5.1.x
  - gemfiles/Gemfile-rails5.2.x
  - gemfiles/Gemfile-rails_edge

matrix:
  allow_failures:
    - rvm: 2.5.3
      gemfile: gemfiles/Gemfile-rails_edge
    - rvm: ruby-head
      gemfile: gemfiles/Gemfile-rails5.0.x
    - rvm: ruby-head
      gemfile: gemfiles/Gemfile-rails5.1.x
    - rvm: ruby-head
      gemfile: gemfiles/Gemfile-rails5.2.x
    - rvm: ruby-head
      gemfile: gemfiles/Gemfile-rails_edge
  exclude:
    - rvm: 2.2.10
      gemfile: gemfiles/Gemfile-rails_edge
    - rvm: 2.3.8
      gemfile: gemfiles/Gemfile-rails_edge
    - rvm: 2.4.5
      gemfile: gemfiles/Gemfile-rails_edge
